name: Build for Windows (GNU)
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
        run:
          shell: pwsh
    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          static: true
          cc: true
          platform: x64

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Install Libman
        run: dotnet tool install -g Microsoft.Web.LibraryManager.Cli

      - run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
      - run: libman --version

      - name: Install Rust nightly with x86_64-pc-windows-gnu target
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --target x86_64-pc-windows-gnu
          source ${HOME}/.cargo/env
      - run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - uses: actions/checkout@master

      - name: Compile
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
          echo "BUILT_ARCHIVE=$(ls target/x86_64-pc-windows-gnu/release/*.exe)" >> $GITHUB_ENV
          echo "BUILT_CHECKSUM=$(sha256sum target/x86_64-pc-windows-gnu/release/*.exe)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ env.BUILT_ARCHIVE }}
            ${{ env.BUILT_CHECKSUM }}